from enum import Enum


class OrchestrationEventType(str, Enum):
    BATCH_CREATED = "BATCH_CREATED"
    DOCUMENT_STAGE_READY = "DOCUMENT_STAGE_READY"
    DOCUMENT_STAGE_PROCESSING = "DOCUMENT_STAGE_PROCESSING"
    DOCUMENT_STAGE_COMPLETED = "DOCUMENT_STAGE_COMPLETED"
    DOCUMENT_STAGE_FAILED = "DOCUMENT_STAGE_FAILED"
    DOCUMENT_STAGE_SKIPPED = "DOCUMENT_STAGE_SKIPPED"
    BATCH_COMPLETED = "BATCH_COMPLETED"
